#!/bin/bash

# so we can use `$CONFIG`, `pubkey` and such
. ./bashrc

tstamp=`bin/tstamp`

_ssh() {
  if [ ! -e "$HOME/.ssh/id_rsa.pub" ]; then
    echo "Looks like you don't have any SSH keys yet. Wanna create them now?"
    read answer
    if [ "$answer" == "yes" -o "$answer" == "y" ]; then
      echo "Usually just hit enter to accept all the defaults."
      ssh-keygen
      clear
      echo "Cut and paste (yes with the mouse) the following to your" | sol yellow
      echo "GitHub -> Settings -> SSH Keys:" | sol yellow
      echo
      pubkey
      echo
    fi
  fi
}

_links() {
  links="
  bash_completion
  bash_profile
  bashrc
  vim
  dircolors
  "

  for i in $links; do 
    target=$HOME/.$i
    if [ -e $target ]; then
      mv $target ${target}.$tstamp
    fi
    ln -fs $CONFIG/$i $target 
  done

  # vim 7.3 (raspi) does not have a 2nd user rc
  if [ -e "$HOME/.vimrc" ]; then
    mv "$HOME/.vimrc" "$HOME/.vimrc.$tstamp"
  fi
  ln -fs $CONFIG/vim/vimrc "$HOME/.vimrc"
}

_git() {
  if [ ! -e "$HOME/.gitconfig" ]; then
    cp gitconfig "$HOME/.gitconfig"
    echo
    echo "Don't forget to change your settings in $HOME/.gitconfig:"
    echo
    cat "$HOME/.gitconfig"
    echo
  fi
}

_tmux() {
  target="$HOME/.tmux.conf"
  if [ -e $target ]; then
    echo "Detected existing $target Skipping."
    return
  fi
  ln -fs $CONFIG/tmux/config $target
}

_emoji() {
  [[ -e "$HOME/.emoji" ]] || echo "🍰 " > "$HOME/.emoji"
}

#####################################################
_ssh
_links
#_git
_tmux
_emoji
